baseURL = 'https://watsonhugo.github.io/'
languageCode = 'zh-TW'
title = '華生的珈琲館'
theme = 'hugo-book'

[pagination]
  pagerSize = 5

[params]
  description = 'History | Geography | Typography'
  BookTheme = 'auto'
  BookSection = 'posts'
  BookSearch = true
  BookDateFormat = 'January 2, 2006'
  BookComments = false

[outputs]
  home = ['HTML', 'RSS']

[markup]
  [markup.highlight]
    style = 'monokai'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    startLevel = 1
