baseURL = 'https://watsonhugo.github.io/'
languageCode = 'zh-TW'
title = '華生的珈琲館'
theme = 'PaperMod'
[pagination]
  pagerSize = 5

[params]
  description = '歷史 | 地理 | 字體排印'
  author = 'Tianchen'
  defaultTheme = 'auto'
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  images = ['/images/avatar.gif']

  [params.homeInfoParams]
    Title = '華生的珈琲館'
    Content = '歷史 | 地理 | 字體排印'

  [[params.socialIcons]]
    name = 'github'
    url = 'https://github.com/watsonhugo'

  [[params.socialIcons]]
    name = 'email'
    url = 'mailto:zhuangtc@gmail.com'

  [[params.socialIcons]]
    name = 'twitter'
    url = 'https://twitter.com/zhuangtc'

[menu]
  [[menu.main]]
    identifier = 'archives'
    name = '歸檔'
    url = '/archives/'
    weight = 10

  [[menu.main]]
    identifier = 'tags'
    name = '標籤'
    url = '/tags/'
    weight = 20

  [[menu.main]]
    identifier = 'about'
    name = '關於我'
    url = '/about/'
    weight = 30

[outputs]
  home = ['HTML', 'RSS', 'JSON']

[markup]
  [markup.highlight]
    style = 'monokai'
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
